name: Build Chain

on: [pull_request]

jobs:
  build-chain:
    concurrency:
      group: pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}      
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [11, 17]
        maven-version: ['3.8.1']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Maven Build
    steps:
      - name: Clean Disk Space
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/disk-space@main
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/long-paths@main
      - name: Java and Maven Setup
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/java@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
      - name: Cache Maven
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/cache-maven@main
        with:
          key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: kiegroup/kogito-pipelines/.ci/actions/build-chain@main1
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/%{process.env.GITHUB_BASE_REF.replace(/(\d*)\.(.*)\.(.*)/g, (m, n1, n2, n3) => `${+n1-7}.${n2}.${n3}`)}/.ci/pull-request-config.yaml
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Surefire Report
        uses: kiegroup/droolsjbpm-build-bootstrap/.ci/actions/surefire-report@main
        if: ${{ always() }}
